apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: proxy-service-cb
  namespace: cinemaabyss
spec:
  host: proxy-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 30s
      maxEjectionPercent: 100
