apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIlJYWm5aVzU1VkdWeWJtOTJiM2s2WjJod1gybEtVMHBpY0ZCV1YyZG9WMFJvVjJsQk9UWlNaMVpCZGxsRFJVUm5jVEJuVDFGb2VBPT0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9
type: kubernetes.io/dockerconfigjson
